import torch
CONFIG= {
    'learning_rate': 0.00001,
    'embedding_dim': 100,
    'hidden_dim': 200,
    'batch_size': 32,
    'eval_batch_size': 32,
    'epoch': 300,
    'random_seed': 1,
    'mask_pro': 0.15,
    'loss_margin': 0.5,
    'num_classes': 20,
    'train_file':'data/20_news/train.txt.src',
    'train_tgt_file':'data/20_news/train.txt.tgt',
    'dev_file':'data/20_news/test.txt.src',
    'dev_oracle_file':'data/20_news/test.txt.tgt',
    'dev_tgt_file':'data/20_news/test.txt.tgt',
    'test_file':'data/20_news/test.txt.src',
    'test_tgt_text_file':'data/20_news/test.txt.tgt',
    'model_path':'results/representation_model.pt',
    'classifier_model_path':'results/classifier_max_pool_finetune_model.pt',
    'classifier_embed_model_path':'results/best_representation_model.pt',
    #'classifier_embed_model_path':None,
    #'load_model_path':'results/sind_best_model_0001.pt',
    'load_model_path':None,
    'exp_name':'runs_20_news/classifier_max_pool_finetune_model',
    'debug':False,
    'device': torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
}
